# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CinemaApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CinemaApp
	pod "DrawerView"
  pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'

end
